### ISSUE TITLE
Type signature is after implementation?

### ISSUE THREAD

**Issue by andys8** [Zelenya/purty#8]
I saw this result of a golden test. Having the type signature in the line after the implementation doesn't look to be intended and might be a bug.

https://github.com/Zelenya/purty/blob/08ae4b835b2ad3513b85ab17fda5031eba2312ce/test/golden/files/original/Where.purs#L8-L9

The change was introduced with https://github.com/Zelenya/purty/commit/08ae4b835b2ad3513b85ab17fda5031eba2312ce

**Comment by Zelenya** [comment]
It's an original/pre-formatted file, it looks good when formatted

**Comment by andys8** [comment]
Oh, the input was changed, but the output still looks fine. That makes sense. Thank you.
